config/routes.rb
IsotopeRails3::Application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  match '/about' => 'users#index', :as => :about_index
  match '/about/:id' => 'users#show', :as => :about
  resources :users
  resources :posts, :path => :blog
  resources :contact

  match '/services' => 'services#index'
  match '/services/phasezero' => 'services#phasezero'
  match '/services/socialmedia' => 'services#socialmedia'
  match '/services/ecommerce' => 'services#ecommerce'
  match '/services/mlm' => 'services#mlm'
  match '/services/financial' => 'services#financial'
  match '/services/insurance' => 'services#insurance'
  match '/services/mobile' => 'services#mobile'
  match '/services/saas' => 'services#saas'

  match '/community' => 'community#index'
  match '/community/xrono' => 'community#xrono'
  match '/community/rubyham' => 'community#rubyham'
  match '/community/state_machine_audits' => 'community#state_machine_audits'
  match '/community/techbirmingham' => 'community#techbirmingham'
  match '/community/contract_acceptance_framework' => 'community#contract_acceptance_framework'
  
  match '/home/contact' => 'home#contact'
  match '/home/payments' => 'home#payments'
  match '/home/careers' => 'home#careers'

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :rememberable, :lockable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :slug, :first_name, :middle_initial, :last_name, :bio, :position, :remember_me, :avatar

  # Paperclip
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "50x50>" }

  has_many :posts
  validates_presence_of :slug, :first_name, :last_name
  validates_uniqueness_of :slug

  before_validation(:on => :create) do
    unless slug
      self.slug = first_name.downcase + '-' + last_name.downcase
    end
  end

  scope :unlocked, where('locked_at IS NULL')

  def to_s
    "#{first_name} #{middle_initial} #{last_name}".squish
  end

  def name
    "#{first_name} #{last_name}"
  end

  def locked
    locked_at?
  end

  def to_param
    slug
  end

  def make_admin!
    self.update_attribute(:admin, true)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :only => [:edit, :update]
  before_filter :require_admin, :only => [:new, :create]

  tab :about

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Registration Successful!"
      redirect_to about_path(@user)
    else
      flash[:error] = "There was a problem creating the user."
      render :new
    end
  end

  def index
    @users = User.unlocked
  end

  def show
    @user = User.find_by_slug(params[:id])
    if @user.locked_at?
      redirect_to root_url
    end
    @posts = Post.for_user(@user).paginate :page => params[:page], :order => 'created_at DESC', :per_page => 5
  end

  def edit
    @user = User.find_by_slug(params[:id])
  end

  def update
    @user = User.find_by_slug(params[:id])

    if admin?
      if params[:user]["locked"] == "true" && !@user.locked_at?
        @user.lock_access!
      elsif params[:user]["locked"] == "false" && @user.locked_at?
        @user.unlock_access!
      end
    else
      params[:user]["locked"].delete if params[:user]["locked"]
    end

    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to about_path(@user)
    else
      flash[:error] = "There was a problem updating the user."
      render :edit
    end
  end
end

app/views/users/_bio.html.haml
.profile
  %h3= link_to_unless_current user, about_path(user)
  %h5= user.position
  %p= user.bio
.profile-pic
  = image_tag user.avatar.url

app/views/users/_form.html.haml
.edit_user
  = form_for @user, :html => { :multipart => true } do |f|
    - if @user.errors.any?
      #error_explanation
        %h2= pluralize(@user.errors.count, "error") + "prohibited this post from being saved:"
        %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg
   
    .field
      = f.label :first_name
      = f.text_field :first_name
    .field
      = f.label :middle_initial
      = f.text_field :middle_initial
    .field
      = f.label :last_name
      = f.text_field :last_name
    .field
      = f.label :email
      = f.text_field :email
    .field
      = f.label :position
      = f.text_field :position
    .field
      = f.label :bio
      = f.text_area :bio
    .clear  
    - if @user == current_user || current_user.admin?
      .field
        = f.label :password
        = f.password_field :password
      .field
        = f.label :password_confirmation
        = f.password_field :password_confirmation
    - if @user.created_at?
      .field
        %p Current Avatar:
        %p= image_tag @user.avatar.url
      .field
        = f.label :avatar
        = f.file_field :avatar
    - if current_user.admin? && @user.created_at?
      .field
        = f.label :lock_user
        = f.radio_button(:locked, :false)
        = f.label :unlocked
        = f.radio_button(:locked, :true)
        = f.label :locked
    .actions
      = f.submit

app/views/users/_post.html.haml
.title
  %h2= link_to post.title, post_path(post)
  %h4
    posted on:
    = post.created_at.to_date
.body
  %p= truncate(post.body, :length => 750)
= link_to "read the rest", post_path(post)
%br

app/views/users/edit.html.haml
%h2= "Editing #{@user}"

= render 'form'

= link_to "Back to Profile", @user

app/views/users/index.html.haml
- content_for :title do 
  About &ndash; Isotope|eleven

#internal-title	
  %h2.typeface-js
    About Us
%p
  Isotope|eleven is a software development firm which specializes in developing web based software applications. It was founded in 2005 and is primarily focused on developing software on Linux based platforms using Ruby on Rails (RoR). Our expert skill sets also include e-commerce, insurance and financial applications, social networking applications (Facebook), database architectures, graphic design, user interfaces and much more. 
%p
  Our clients range from small businesses to large financial firms, insurance companies as well as government agencies. We believe in transparent development and in keeping our clients informed about each project’s status. To that end, we employ many technologies to keep our client informed in near real-time and practice the AGILE methodology of development which includes constant communication and deliverables. We strive to build long term relationships and to deliver software on time and on target.
%h2
  Meet The Team

- @users.each do |user|
  = render :partial => 'bio', :locals => {:user => user}

app/views/users/new.html.haml
%h2 New User

= render 'form'

= link_to 'Back', users_path

app/views/users/show.html.haml
= render :partial => "bio", :locals => { :user => @user }
- if current_user && (current_user == @user || current_user.admin?)
  .clear
  %p= link_to 'Edit User', edit_user_path

.clear
- unless @posts.empty?
  %h2 Blog Posts
  = render @posts
  = will_paginate @posts