config/routes.rb
IsotopeRails3::Application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  match '/about' => 'users#index', :as => :about_index
  match '/about/:id' => 'users#show', :as => :about
  resources :users
  resources :posts, :path => :blog
  resources :contact

  match '/services' => 'services#index'
  match '/services/phasezero' => 'services#phasezero'
  match '/services/socialmedia' => 'services#socialmedia'
  match '/services/ecommerce' => 'services#ecommerce'
  match '/services/mlm' => 'services#mlm'
  match '/services/financial' => 'services#financial'
  match '/services/insurance' => 'services#insurance'
  match '/services/mobile' => 'services#mobile'
  match '/services/saas' => 'services#saas'

  match '/community' => 'community#index'
  match '/community/xrono' => 'community#xrono'
  match '/community/rubyham' => 'community#rubyham'
  match '/community/state_machine_audits' => 'community#state_machine_audits'
  match '/community/techbirmingham' => 'community#techbirmingham'
  match '/community/contract_acceptance_framework' => 'community#contract_acceptance_framework'
  
  match '/home/contact' => 'home#contact'
  match '/home/payments' => 'home#payments'
  match '/home/careers' => 'home#careers'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title, :body, :user_id, :slug
  validates_uniqueness_of :slug
  validates_format_of :slug, :with => /^[a-zA-Z0-9\-]+$/, :message => " can only contain letters, numbers, and dashes."

  # TODO validate title is all characters
  validates_uniqueness_of :title
  scope :for_user, lambda{ |user| where('user_id = ?', user.id)}

  def to_param
    self.slug
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :authorized_user, :only => [:edit, :update, :destroy]

  tab :blog

  def index
    @posts = Post.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
      format.json { render :json => @posts }
      format.atom
    end
  end

  def show
    @post = Post.find_by_slug(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @post }
    end
  end

  def edit
    @post = Post.find_by_slug(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to(post_path(@post), :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find_by_slug(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(post_path(@post), :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find_by_slug(params[:id])
    if @post.destroy
      redirect_to(posts_url, :notice => 'Post was successfully destroyed.')
    end
  end

  ######################################################################
  private
  ######################################################################

  def authorized_user
    post = Post.find_by_slug(params[:id])
    unless post.user == current_user || admin?
      flash[:error] = 'You must be the creator or an admin to do that'
      redirect_to root_path
    end
  end

end

app/views/posts/_form.html.haml
.edit_post
  = form_for(@post) do |f|
    - if @post.errors.any?
      #error_explanation
        %h2= pluralize(@post.errors.count, "error") + "prohibited this post from being saved:"
        %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

    .field
      = f.label :title
      = f.text_field :title
    .field
      = f.label :slug
      = f.text_field :slug
    .field
      = f.label :body
      = f.text_area :body
    .clear  
    .actions
      = f.submit

app/views/posts/_post.html.haml
= div_for post do
  .blog_post
    .blog_info_top
      = image_tag post.user.avatar.url(:thumb)
      %h2= link_to_unless_current h(post.title), post
      .author
        %h3
          by:
          = link_to_unless_current post.user, about_path(post.user) 
        %p
          = post.created_at.to_formatted_s(:long_ordinal)
      .clear
    .blog_content
      =coderay(post.body.html_safe)

app/views/posts/edit.html.haml
%h2 Editing post

= render 'form'

= link_to 'Show', @post
|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
- content_for(:title, "Blog &ndash; Isotope|eleven".html_safe)
%h2
  Blog
  %span#rss_link= link_to (image_tag 'feed-icon-28x28.png'), posts_path(:atom)

= render @posts
= will_paginate @posts

- if current_user
  = link_to 'New Post', new_post_path

app/views/posts/new.html.erb
<h2>New post</h2>

<%= render 'form' %>

<%= link_to 'Back', posts_path, :class => 'content_link' %>

app/views/posts/show.html.haml
- content_for(:title, "#{@post.title} &ndash; Blog &ndash; Isotope|eleven".html_safe)
= render :partial => @post
%p
  = link_to "View All Posts", posts_path
- if current_user && (current_user == @post.user || current_user.admin?)
  %p= link_to 'Edit', edit_post_path(@post)
- if current_user && current_user.admin?
  %p= button_to 'Destroy', @post, :method => :delete, :confirm => "Are you sure?"