config/routes.rb
IsotopeRails3::Application.routes.draw do
  root :to => 'home#index'

  devise_for :users, :path => '/', :path_names => { :sign_in => 'login', :sign_out => 'logout' }

  match '/about' => 'users#index', :as => :about_index
  match '/about/:id' => 'users#show', :as => :about
  resources :users
  resources :posts, :path => :blog
  resources :contact

  match '/services' => 'services#index'
  match '/services/phasezero' => 'services#phasezero'
  match '/services/socialmedia' => 'services#socialmedia'
  match '/services/ecommerce' => 'services#ecommerce'
  match '/services/mlm' => 'services#mlm'
  match '/services/financial' => 'services#financial'
  match '/services/insurance' => 'services#insurance'
  match '/services/mobile' => 'services#mobile'
  match '/services/saas' => 'services#saas'

  match '/community' => 'community#index'
  match '/community/xrono' => 'community#xrono'
  match '/community/rubyham' => 'community#rubyham'
  match '/community/state_machine_audits' => 'community#state_machine_audits'
  match '/community/techbirmingham' => 'community#techbirmingham'
  match '/community/contract_acceptance_framework' => 'community#contract_acceptance_framework'
  
  match '/home/contact' => 'home#contact'
  match '/home/payments' => 'home#payments'
  match '/home/careers' => 'home#careers'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :email
  after_create :send_email

  def send_email
    ContactMailer.contact_email(self).deliver
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  before_filter :require_admin, :only => [:show, :edit]

  def index
    if admin?
      @contacts = Contact.all
    else
      @contact = Contact.new
    end
  end

  def show
      @contact = Contact.find(params[:id])
  end

  def create
    if @contact = Contact.create(params[:contact])
      render :action => 'thank_you'
    else
      flash[:error] = "There were problems sending the message."
      redirect_to :action => 'index'
    end
  end

  def edit
      @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(params[:contact])
      flash[:notice] = "Message was successfully updated."
      redirect_to :action => 'index'
    else
      flash[:error] = "There was a problem updating the message."
      redirect_to :action => 'index'
    end
  end

  def thank_you
  end

  def destroy
    @contact = Contact.find(params[:id])
    if @contact.destroy
      flash[:notice] = "Message was successfully deleted."
      redirect_to :action => 'index'
    else
      flash[:error] = "There was a problem deleting the message."
      redirect_to :action => 'index'
    end
  end

end

app/views/contact/_contact_form.html.haml
= f.label :nickname
= f.text_field :nickname
%br
= f.label :email
= f.text_field :email
%br
= f.label :company
= f.text_field :company
%br
= label_tag :description
= f.text_area :text
%br
= f.submit

app/views/contact/_form.html.haml
%blockquote
  %fieldset
    Hey! My name is
    %input{:type => 'text', :name => 'contact[nickname]', :id => "contact_nickname"}
    and I was hoping to talk to you guys in order to
    %input{:type => 'text', :name => 'contact[text]', :class => "description-field", :id => "contact_text"}
    %br
    %br
      By the way, my contact email address is
    %input{:type => 'text', :name => 'contact[email]', :id => "contact_email"}
    and I work with
    %input{:type => 'text', :name => 'contact[company]', :id => "contact_company", :value => ''}
    %br
    %br
    %button{:type => "submit"}
      Submit

app/views/contact/edit.html.haml
- @contact_forms.each do |contact_form|
  - form_tag contact_form do |f|
    = render :partial => 'contact_form', :locals => { :f => f }

app/views/contact/index.html.haml
- content_for :title do
  Contact &ndash; Isotope|eleven 
#internal-title
.content-left
  %img{:src => "/images/contact-img.png", :alt => "contact image"} 
  %p{:class => "contact-title"}
    Isotope|eleven
  %p
    529 Beacon Pkwy W - Suite 105
    %br 
    Birmingham, AL 35209
    %br
    p: 877.476.8671
    %br 
    f: 205.943.5760
    %br 
    e:
    %a{:href => "mailto:info@isotope11.com"}
      info@isotope11.com

- unless current_user && current_user.admin?
  %h2{:class => "typeface-js"}
    Contact Us
  %p  For business inquiries, please contact us directly or just fill out our simple contact form
  %br 
  %br 

  = form_tag :action => 'create' do |f|
    = render 'form'

- if current_user && current_user.admin?
  %table
    %thead
      %th Contact Name
      %th Contact Email
      %th Contact Company
      %th Contact Note
    - @contacts.each do |contact|
      %tr
        %td= link_to contact.nickname, contact_path(contact)
        %td= contact.email
        %td= contact.company
        %td= contact.text
    /- form_for contact do |f|
    /  = render :partial => 'contact_form', :locals => { :f => f }

app/views/contact/list.html.haml
- @contact_forms.each do |form|
  = form.nickname

app/views/contact/show.html.haml
- form_for @contact do |f|
  = render :partial => 'contact_form', :locals => { :f => f }
  = button_to "Delete", options = { :action => 'destroy' , :id => @contact }, html_options = { :confirm => "Are you sure?", :method => :delete }

app/views/contact/thank_you.html.haml
%p Thank you for contacting us. We will contact you back shortly.